// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUw2YJoTRS1bbc-2du9NIOYOWOSFirFB8',
    appId: '1:1034228384766:web:e5eafe6a5783bdae4ab6af',
    messagingSenderId: '1034228384766',
    projectId: 'ctis470-project',
    authDomain: 'ctis470-project.firebaseapp.com',
    storageBucket: 'ctis470-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjVfFxQNcHpeUyYq_ZivJKFxl1O47f-mM',
    appId: '1:1034228384766:android:88d35937123161a04ab6af',
    messagingSenderId: '1034228384766',
    projectId: 'ctis470-project',
    storageBucket: 'ctis470-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAORoM0s3lUVu9MnsKMQpisM3bwbFbPfDI',
    appId: '1:1034228384766:ios:8fd8a0a9d861af274ab6af',
    messagingSenderId: '1034228384766',
    projectId: 'ctis470-project',
    storageBucket: 'ctis470-project.firebasestorage.app',
    iosClientId:
        '1034228384766-ocuu6nsnf44ilj0mo4ml5t7rpna69mkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctisDictionary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAORoM0s3lUVu9MnsKMQpisM3bwbFbPfDI',
    appId: '1:1034228384766:ios:8fd8a0a9d861af274ab6af',
    messagingSenderId: '1034228384766',
    projectId: 'ctis470-project',
    storageBucket: 'ctis470-project.firebasestorage.app',
    iosClientId:
        '1034228384766-ocuu6nsnf44ilj0mo4ml5t7rpna69mkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctisDictionary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUw2YJoTRS1bbc-2du9NIOYOWOSFirFB8',
    appId: '1:1034228384766:web:647980a1d57d89f44ab6af',
    messagingSenderId: '1034228384766',
    projectId: 'ctis470-project',
    authDomain: 'ctis470-project.firebaseapp.com',
    storageBucket: 'ctis470-project.firebasestorage.app',
  );
}
